In [20]:
from __future__ import division, print_function
from os import sys
sys.path.append('cpresources')
from numpy.linalg import solve
from numpy import  array, empty, zeros

from banded import banded

# Test with 6 elements

N = 6
U = 5

A = array([
	[3, -1, -1, 0, 0, 0],
	[-1, 4, -1, -1, 0, 0],
	[-1,-1, 4, -1, -1, 0],
	[0, -1,-1, 4, -1, -1],
	[0, 0, -1,-1, 4, -1],
	[0, 0, 0, -1, -1, 3]
],float)

v = array([U, U, 0, 0, 0, 0],float)

x = solve(A,v)
print(x)

# Banded example

#N = 10000
Ab = empty((5,N),float)
vb = zeros(N,float)

vb[[0,1]] = U

Ab[:,:] = -1
Ab[2,:] = 4
Ab[2,0] = 3
Ab[2,N-1] = 3

[3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]


In [22]:
A

array([[ 3., -1., -1.,  0.,  0.,  0.],
       [-1.,  4., -1., -1.,  0.,  0.],
       [-1., -1.,  4., -1., -1.,  0.],
       [ 0., -1., -1.,  4., -1., -1.],
       [ 0.,  0., -1., -1.,  4., -1.],
       [ 0.,  0.,  0., -1., -1.,  3.]])

In [43]:
up = 2
down = 2
n = A.shape[0]

banded_matrix = np.ones((1+up+down, n))

for i in range(n):
    middle = int(n/2-1)
    # Diagonal
    banded_matrix[middle,i] = A[i,i]

    # Upper
    for j in range(1,up+1):
        try:
            banded_matrix[middle+j,i] = A[i+j,i]
        except:            
            pass
        
    
    # Lower
    for j in range(1,down+1):
        try:
            banded_matrix[middle-j,i] = A[i-j,i]
        except:
            pass




print(banded_matrix)

[[ 0.  0. -1. -1. -1. -1.]
 [ 0. -1. -1. -1. -1. -1.]
 [ 3.  4.  4.  4.  4.  3.]
 [-1. -1. -1. -1. -1.  1.]
 [-1. -1. -1. -1.  1.  1.]]


In [23]:
Ab

array([[-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.],
       [ 3.,  4.,  4.,  4.,  4.,  3.],
       [-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.]])

In [21]:
banded(Ab, vb, 2, 2)

array([3.7254902 , 3.43137255, 2.74509804, 2.25490196, 1.56862745,
       1.2745098 ])

In [12]:
vb

array([5., 5., 0., ..., 0., 0., 0.])

In [13]:
A

array([[ 3., -1., -1.,  0.,  0.,  0.],
       [-1.,  4., -1., -1.,  0.,  0.],
       [-1., -1.,  4., -1., -1.,  0.],
       [ 0., -1., -1.,  4., -1., -1.],
       [ 0.,  0., -1., -1.,  4., -1.],
       [ 0.,  0.,  0., -1., -1.,  3.]])

In [17]:
Ab

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [ 3.,  4.,  4., ...,  4.,  4.,  3.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]])

In [16]:
banded(A, v, 1, 1)

array([nan, nan, nan, nan, nan, nan])

In [7]:
import numpy as np

def definir_sistema(N=26, C=1, m=1, k=6, w=2):
  # alpha
  a=2*k-m*w**2
  # Construção da matriz solução
  solucao=np.empty([N],dtype=np.float64)
  solucao[0]=C
  for i in range(1,N):
    solucao[i]=0

  ## Construção matriz do sistema
  # Inicializar a zeros
  matriz=np.zeros([N,N],dtype=np.float64)

  # Primeiro peso
  matriz[0][0]=a-k
  matriz[0][1]=-k

  # Ultimo peso
  matriz[-1][-1]=a-k
  matriz[-1][-2]=-k

  # Pesos restantes
  for i in range(1,N-1):
    matriz[i][i]=a
    matriz[i][i-1]=-k
    matriz[i][i+1]=-k
  return matriz, solucao 

In [10]:
matriz, solucao = definir_sistema(N=int(1e2))

banded(matriz, solucao, 1,1)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan])